Friend Module PassagewayDoors
    Friend PASSAGEWAYDOOR_MAPS As New List(Of MapData)
    Sub Initialize()
        PASSAGEWAYDOOR_MAPS.Clear()
        PASSAGEWAYDOOR_MAPS.Add(LOAD_RESOURCE("PASSAGEWAYDOOR1.map"))
        PASSAGEWAYDOOR_MAPS.Add(LOAD_RESOURCE("PASSAGEWAYDOOR2.map"))
        PASSAGEWAYDOOR_MAPS.Add(LOAD_RESOURCE("PASSAGEWAYDOOR4.map"))
        PASSAGEWAYDOOR_MAPS.Add(LOAD_RESOURCE("PASSAGEWAYDOOR8.map"))
    End Sub
End Module
