Friend Module Chambers
    Friend CHAMBER_MAPS As New List(Of MapData)
    Sub Initialize()
        CHAMBER_MAPS.Clear()
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER0.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER1.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER2.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER3.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER4.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER5.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER6.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER7.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER8.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER9.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER10.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER11.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER12.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER13.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER14.map"))
        CHAMBER_MAPS.Add(LOAD_RESOURCE("Assets/CHAMBER15.map"))
    End Sub
End Module
