Friend Module PassagewayDoors
    Friend PASSAGEWAYDOOR_MAPS As New List(Of MapData)
    Sub Initialize()
        PASSAGEWAYDOOR_MAPS.Clear()
        PASSAGEWAYDOOR_MAPS.Add(LOAD_RESOURCE("Assets/PASSAGEWAYDOOR1.map"))
        PASSAGEWAYDOOR_MAPS.Add(LOAD_RESOURCE("Assets/PASSAGEWAYDOOR2.map"))
        PASSAGEWAYDOOR_MAPS.Add(LOAD_RESOURCE("Assets/PASSAGEWAYDOOR4.map"))
        PASSAGEWAYDOOR_MAPS.Add(LOAD_RESOURCE("Assets/PASSAGEWAYDOOR8.map"))
    End Sub
End Module
