Friend Enum TerrainIdentifier
    EMPTY
    SOLID
    FLOOR
    BLOOD
    WALL_NORTH
    WALL_EAST
    WALL_SOUTH
    WALL_WEST
    CORNER_INSIDE_NORTHEAST
    CORNER_INSIDE_SOUTHEAST
    CORNER_INSIDE_SOUTHWEST
    CORNER_INSIDE_NORTHWEST
    CORNER_OUTSIDE_NORTHEAST
    CORNER_OUTSIDE_SOUTHEAST
    CORNER_OUTSIDE_SOUTHWEST
    CORNER_OUTSIDE_NORTHWEST
    DOOR_NORTH
    DOOR_EAST
    DOOR_SOUTH
    DOOR_WEST
    GRASS
End Enum
