Friend Enum TerrainIdentifier
    EMPTY
    SOLID
    FLOOR
    BLOOD
    WALL_NORTH
    WALL_EAST
    WALL_SOUTH
    WALL_WEST
    WALL_CORNER_INSIDE_NORTHEAST
    WALL_CORNER_INSIDE_SOUTHEAST
    WALL_CORNER_INSIDE_SOUTHWEST
    WALL_CORNER_INSIDE_NORTHWEST
    WALL_CORNER_OUTSIDE_NORTHEAST
    WALL_CORNER_OUTSIDE_SOUTHEAST
    WALL_CORNER_OUTSIDE_SOUTHWEST
    WALL_CORNER_OUTSIDE_NORTHWEST
    DOOR_NORTH
    DOOR_EAST
    DOOR_SOUTH
    DOOR_WEST
    GRASS
End Enum
